// <auto-generated />
using cep.api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace cep.api.Migrations
{
    [DbContext(typeof(CepDbContext))]
    partial class CepDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("cep.api.Data.Entities.Endereco", b =>
                {
                    b.Property<string>("Cep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Cep");

                    b.HasIndex("Uf");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("cep.api.Data.Entities.Estado", b =>
                {
                    b.Property<string>("Sigla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Sigla");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("cep.api.Data.Entities.Endereco", b =>
                {
                    b.HasOne("cep.api.Data.Entities.Estado", "Estado")
                        .WithMany("Enderecos")
                        .HasForeignKey("Uf")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
